"""Add PostSocialAccount and BusinessAssignment tables, add Post.timezone

Revision ID: 3f04ee66dc4c
Revises: 7cf238c4ad45
Create Date: 2026-07-19 22:50:36.545299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f04ee66dc4c'
down_revision: Union[str, Sequence[str], None] = '7cf238c4ad45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_user_id', sa.Integer(), nullable=False),
    sa.Column('marketing_team_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marketing_team_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_user_id', name='uq_business_user_single_team')
    )
    op.create_index(op.f('ix_business_assignments_business_user_id'), 'business_assignments', ['business_user_id'], unique=False)
    op.create_index(op.f('ix_business_assignments_marketing_team_id'), 'business_assignments', ['marketing_team_id'], unique=False)
    op.create_table('post_social_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('social_account_id', sa.Integer(), nullable=False),
    sa.Column('publish_status', sa.Enum('scheduled', 'published', 'failed', 'cancelled', 'pending_approval', name='publish_status', native_enum=False, length=20), nullable=False),
    sa.Column('platform_post_id', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('published_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['social_account_id'], ['socialaccounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'social_account_id', name='uq_post_social_account')
    )
    op.create_index(op.f('ix_post_social_accounts_post_id'), 'post_social_accounts', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_social_accounts_social_account_id'), 'post_social_accounts', ['social_account_id'], unique=False)
    op.add_column('posts', sa.Column('timezone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'timezone')
    op.drop_index(op.f('ix_post_social_accounts_social_account_id'), table_name='post_social_accounts')
    op.drop_index(op.f('ix_post_social_accounts_post_id'), table_name='post_social_accounts')
    op.drop_table('post_social_accounts')
    op.drop_index(op.f('ix_business_assignments_marketing_team_id'), table_name='business_assignments')
    op.drop_index(op.f('ix_business_assignments_business_user_id'), table_name='business_assignments')
    op.drop_table('business_assignments')
    # ### end Alembic commands ###
