"""create campaigns table

Revision ID: 3fee43ff6cf1
Revises: b93903a6e12a
Create Date: 2026-07-07 16:33:40.272919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fee43ff6cf1'
down_revision: Union[str, Sequence[str], None] = 'b93903a6e12a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('campaigns', sa.Column('title', sa.String(length=100), nullable=False))
    op.add_column('campaigns', sa.Column('description', sa.String(length=300), nullable=False))
    op.add_column('campaigns', sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('campaigns', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('campaigns', sa.Column('status', sa.String(length=10), nullable=False))
    op.add_column('campaigns', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('campaigns', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint(None, 'campaigns', ['title'])
    op.create_unique_constraint(None, 'campaigns', ['description'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campaigns', type_='unique')
    op.drop_constraint(None, 'campaigns', type_='unique')
    op.drop_column('campaigns', 'updated_at')
    op.drop_column('campaigns', 'created_at')
    op.drop_column('campaigns', 'status')
    op.drop_column('campaigns', 'end_date')
    op.drop_column('campaigns', 'start_date')
    op.drop_column('campaigns', 'description')
    op.drop_column('campaigns', 'title')
    op.drop_column('campaigns', 'user_id')
    # ### end Alembic commands ###
