"""...

Revision ID: 9039846b9ef6
Revises: 
Create Date: 2026-07-25 17:06:01.977620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9039846b9ef6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_social_accounts_post_id'), table_name='post_social_accounts')
    op.drop_index(op.f('ix_post_social_accounts_social_account_id'), table_name='post_social_accounts')
    op.drop_table('post_social_accounts')
    op.drop_column('posts', 'timezone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('timezone', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_table('post_social_accounts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('social_account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('publish_status', sa.VARCHAR(length=20), server_default=sa.text("'scheduled'::character varying"), autoincrement=False, nullable=False),
    sa.Column('platform_post_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('published_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('post_social_accounts_post_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['social_account_id'], ['socialaccounts.id'], name=op.f('post_social_accounts_social_account_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('post_social_accounts_pkey')),
    sa.UniqueConstraint('post_id', 'social_account_id', name=op.f('uq_post_social_account'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_post_social_accounts_social_account_id'), 'post_social_accounts', ['social_account_id'], unique=False)
    op.create_index(op.f('ix_post_social_accounts_post_id'), 'post_social_accounts', ['post_id'], unique=False)
    # ### end Alembic commands ###
