"""create social_account table

Revision ID: b93903a6e12a
Revises: 
Create Date: 2026-07-07 16:03:43.189003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b93903a6e12a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('socialaccounts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('socialaccounts', sa.Column('platform', sa.String(length=9), nullable=False))
    op.add_column('socialaccounts', sa.Column('account_name', sa.String(length=100), nullable=False))
    op.add_column('socialaccounts', sa.Column('account_id', sa.String(length=255), nullable=False))
    op.add_column('socialaccounts', sa.Column('access_token', sa.Text(), nullable=False))
    op.add_column('socialaccounts', sa.Column('refresh_token', sa.Text(), nullable=True))
    op.add_column('socialaccounts', sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True))
    op.add_column('socialaccounts', sa.Column('profile_picture', sa.String(length=500), nullable=True))
    op.add_column('socialaccounts', sa.Column('is_connected', sa.Boolean(), nullable=False))
    op.add_column('socialaccounts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('socialaccounts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('socialaccounts', 'updated_at')
    op.drop_column('socialaccounts', 'created_at')
    op.drop_column('socialaccounts', 'is_connected')
    op.drop_column('socialaccounts', 'profile_picture')
    op.drop_column('socialaccounts', 'token_expiry')
    op.drop_column('socialaccounts', 'refresh_token')
    op.drop_column('socialaccounts', 'access_token')
    op.drop_column('socialaccounts', 'account_id')
    op.drop_column('socialaccounts', 'account_name')
    op.drop_column('socialaccounts', 'platform')
    op.drop_column('socialaccounts', 'user_id')
    # ### end Alembic commands ###
