"""create tables

Revision ID: e36d1e176da4
Revises: 3fee43ff6cf1
Create Date: 2026-07-07 18:22:25.240628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e36d1e176da4'
down_revision: Union[str, Sequence[str], None] = '3fee43ff6cf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('notifications', sa.Column('title', sa.String(length=40), nullable=False))
    op.add_column('notifications', sa.Column('description', sa.String(length=120), nullable=False))
    op.add_column('notifications', sa.Column('type', sa.String(length=7), nullable=False))
    op.add_column('notifications', sa.Column('is_read', sa.Boolean(), nullable=False))
    op.add_column('notifications', sa.Column('related_post_id', sa.String(length=20), nullable=True))
    op.add_column('notifications', sa.Column('related_campaign_id', sa.String(length=20), nullable=True))
    op.add_column('notifications', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('posts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('posts', sa.Column('campaign_id', sa.Integer(), nullable=False))
    op.add_column('posts', sa.Column('media_url', sa.String(length=200), nullable=False))
    op.add_column('posts', sa.Column('media_type', sa.String(length=12), nullable=False))
    op.add_column('posts', sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('posts', sa.Column('published_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('posts', sa.Column('status', sa.String(length=10), nullable=False))
    op.add_column('posts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('posts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('schedules', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('schedules', sa.Column('celery_task_id', sa.String(length=10), nullable=False))
    op.add_column('schedules', sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('schedules', sa.Column('executed_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('schedules', sa.Column('status', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'status')
    op.drop_column('schedules', 'executed_time')
    op.drop_column('schedules', 'scheduled_time')
    op.drop_column('schedules', 'celery_task_id')
    op.drop_column('schedules', 'user_id')
    op.drop_column('posts', 'updated_at')
    op.drop_column('posts', 'created_at')
    op.drop_column('posts', 'status')
    op.drop_column('posts', 'published_time')
    op.drop_column('posts', 'scheduled_time')
    op.drop_column('posts', 'media_type')
    op.drop_column('posts', 'media_url')
    op.drop_column('posts', 'campaign_id')
    op.drop_column('posts', 'user_id')
    op.drop_column('notifications', 'created_at')
    op.drop_column('notifications', 'related_campaign_id')
    op.drop_column('notifications', 'related_post_id')
    op.drop_column('notifications', 'is_read')
    op.drop_column('notifications', 'type')
    op.drop_column('notifications', 'description')
    op.drop_column('notifications', 'title')
    op.drop_column('notifications', 'user_id')
    # ### end Alembic commands ###
