"""Create publishing_logs table

Revision ID: e44cf1f35dbd
Revises: 
Create Date: 2026-08-06 19:21:41.851193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e44cf1f35dbd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_social_accounts')
    op.drop_table('client_social_accounts')
    op.drop_index(op.f('ix_business_assignments_business_user_id'), table_name='business_assignments')
    op.drop_index(op.f('ix_business_assignments_marketing_team_id'), table_name='business_assignments')
    op.drop_table('business_assignments')
    op.drop_column('posts', 'timezone')
    op.drop_column('posts', 'media_urls')
    op.drop_column('users', 'website')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('media_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('timezone', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_table('business_assignments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('business_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('marketing_team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['business_user_id'], ['users.id'], name=op.f('business_assignments_business_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marketing_team_id'], ['users.id'], name=op.f('business_assignments_marketing_team_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('business_assignments_pkey')),
    sa.UniqueConstraint('business_user_id', name=op.f('uq_business_user_single_team'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_business_assignments_marketing_team_id'), 'business_assignments', ['marketing_team_id'], unique=False)
    op.create_index(op.f('ix_business_assignments_business_user_id'), 'business_assignments', ['business_user_id'], unique=False)
    op.create_table('client_social_accounts',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('platform_username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('client_social_accounts_pkey'))
    )
    op.create_table('post_social_accounts',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('social_account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('publish_status', sa.VARCHAR(length=20), server_default=sa.text("'scheduled'::character varying"), autoincrement=False, nullable=False),
    sa.Column('platform_post_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('published_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('post_social_accounts_post_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['social_account_id'], ['socialaccounts.id'], name=op.f('post_social_accounts_social_account_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('post_social_accounts_pkey')),
    sa.UniqueConstraint('post_id', 'social_account_id', name=op.f('uq_post_social_account'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
